apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-registrations
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amine250/k8s-gitops-bootstrap
    targetRevision: main
    path: clusters
    kustomize:
      commonLabels:
        app.kubernetes.io/managed-by: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
