apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: ""
  server: ""
  config: |
    {
      "tlsClientConfig": {
        "certData": "",
        "keyData": "",
        "caData": ""
      }
    }